spring:
  application:
    name: Eureka Client


server:
  port: 8501


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8505/eureka
  instance:
    hostname: localhost
